### ISSUE TITLE
Should allow specifying user or user id instead of being hard coded to 33

### ISSUE THREAD

**Issue by Willamin** [t-richards/permfixer#1]

**Comment by t-richards** [comment]
@Willamin What should command-line interface for this look like?

**Comment by Willamin** [comment]
It should default to myself.
It should let me specify a user name (then look it up).
It should let me specify a user id.
It should let me specify a group name (then look it up).
It should let me specify a group id.

**Comment by t-richards** [comment]
Implemented as of 45c48290ba0c3d573381c34c9fcd7800f7003415
